import { mkdir, readFile, writeFile } from "node:fs/promises"
import { homedir } from "node:os"
import { dirname, join } from "node:path"
import type { Editor } from "../kernel/editor"
import type { Evaluator } from "../runtime/evaluator"
import { getCustomizedFaceOverrides } from "../runtime/faces"
import { getBuiltinTheme, listEnabledBuiltinThemes, listSavedBuiltinThemes } from "../themes"

export function customFilePath(): string {
  return join(homedir(), ".jemacs", "custom.ts")
}

export async function loadCustomFile(editor: Editor, evaluator: Evaluator): Promise<void> {
  const path = customFilePath()
  try {
    const source = await readFile(path, "utf8")
    await evaluator.eval(source, path)
    const active = listEnabledBuiltinThemes().at(-1)
    if (active) {
      const theme = getBuiltinTheme(active)
      if (theme) editor.setTheme(theme)
    }
    editor.refreshComposedTheme()
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error
  }
}

export async function saveCustomFile(): Promise<void> {
  const path = customFilePath()
  await mkdir(dirname(path), { recursive: true })
  const lines = [
    "// Generated by customize-save-customized — edits may be overwritten.",
    "",
  ]
  for (const theme of listSavedBuiltinThemes()) {
    lines.push(`enableBuiltinTheme(${JSON.stringify(theme)})`)
  }
  for (const { name, style } of getCustomizedFaceOverrides()) {
    for (const [attr, value] of Object.entries(style)) {
      if (attr === "inherit") continue
      lines.push(`setFaceAttribute(${JSON.stringify(name)}, ${JSON.stringify(attr)}, ${JSON.stringify(value)})`)
    }
  }
  if (lines.at(-1) !== "") lines.push("")
  await writeFile(path, lines.join("\n"), "utf8")
}
